sudo: false
language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - node_modules

os:
  - osx
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - yarn install
  - yarn run vscode:prepublish

script:
  - yarn test --silent
